SELECT NMPRODUCT, SUPPLIER.NMSUPPLIER, VLPRICE, (VLPRICE - VLPRICE * 0.10) AS VL10DISCOUNT, (VLPRICE - VLPRICE * 0.20)AS VL20DISCOUNT, (VLPRICE - VLPRICE * 0.30) AS VL30DISCOUNT 
FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER  
WHERE (VLPRICE - VLPRICE * 0.10) > 15 ORDER BY VLPRICE ASC, NMPRODUCT ASC;

SELECT NMPRODUCT, SUPPLIER.NMSUPPLIER, VLPRICE, (VLPRICE * QTSTOCK) AS VLTOTAL, (VLPRICE * (QTSTOCK * 2)) AS VLTOTALDOUBLE FROM PRODUCT 
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER WHERE (VLPRICE * QTSTOCK) > 12000 ORDER BY SUPPLIER.NMSUPPLIER, NMPRODUCT;

SELECT * FROM CUSTOMER WHERE NMCUSTOMER LIKE 'J%' AND IDFONE IS NOT NULL;

SELECT NMPRODUCT, VLPRICE, SUPPLIER.NMSUPPLIER FROM PRODUCT 
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER WHERE SUPPLIER.NMSUPPLIER LIKE '%ica%';

SELECT SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE, NMPRODUCT, VLPRICE, (VLPRICE * QTSTOCK) AS VLTOTAL FROM PRODUCT 
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE NMPRODUCT LIKE 'S%' AND VLPRICE > 50 ORDER BY SUPPLIER.NMSUPPLIER, VLPRICE;

SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, REQUEST.DTREQUEST, REQUEST.DTDELIVER, QTAMOUNT, VLUNITARY FROM PRODUCTREQUEST 
INNER JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
WHERE  QTAMOUNT < 600 AND DTREQUEST >= '2003-06-01' AND DTREQUEST <= '2003-06-30' AND NMPRODUCT LIKE 'M%';

SELECT CUSTOMER.NMADRESS, PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, REQUEST.DTREQUEST, REQUEST.DTDELIVER, REQUEST.VLTOTAL FROM PRODUCTREQUEST 
INNER JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
WHERE SUPPLIER.IDFONE LIKE '(011)%' AND VLTOTAL > 20 ORDER BY NMSUPPLIER;