SELECT NMCUSTOMER, IDFONE FROM CUSTOMER WHERE IDFONE LIKE '4%';
SELECT * FROM CUSTOMER WHERE IDFONE = NULL OR IDFONE = 'DESCONHECIDO';
SELECT NMSUPPLIER, IDFONE FROM SUPPLIER WHERE IDFONE NOT LIKE '(%)%';
SELECT NMPRODUCT, QTSTOCK, (VLPRICE - (VLPRICE * 0.1)) AS VLDISCOUNT FROM PRODUCT WHERE QTSTOCK > 2000;
SELECT NMPRODUCT, VLPRICE FROM PRODUCT WHERE VLPRICE >= 10 AND VLPRICE <= 20;
SELECT NMPRODUCT, VLPRICE, (VLPRICE * QTSTOCK) AS TOPRICE FROM PRODUCT WHERE VLPRICE > 50;
SELECT NMPRODUCT, SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER;
SELECT CUSTOMER.NMCUSTOMER, DTREQUEST, VLTOTAL FROM REQUEST INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER WHERE DTREQUEST >=	'2003-06-01' AND DTDELIVER <= '2003-07-31';

SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, QTAMOUNT, VLUNITARY, (VLUNITARY * QTAMOUNT) AS VLTOTAL FROM PRODUCTREQUEST 
INNER JOIN  PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
INNER JOIN REQUEST ON  PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
WHERE QTAMOUNT >= 500;