SELECT NMPRODUCT, COUNT(PRODUCTREQUEST.CDPRODUCT) AS TIMESBOUGHT FROM PRODUCT LEFT JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT GROUP BY NMPRODUCT ORDER BY NMPRODUCT;
SELECT NMSUPPLIER, COUNT(PRODUCT.CDSUPPLIER) FROM SUPPLIER LEFT JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER GROUP BY NMSUPPLIER ORDER BY NMSUPPLIER;

SELECT SUPPLIER.NMSUPPLIER, CASE 
WHEN GROUPING(PRODUCT.NMPRODUCT) = 1 THEN 'TOTAL' 
ELSE NMPRODUCT END AS NMPRODUCT , 
SUM(PRODUCT.CDPRODUCT) AS TOTALBOUGHT
FROM PRODUCTREQUEST  
FULL JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
FULL JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY ROLLUP(NMSUPPLIER, NMPRODUCT)
ORDER BY NMSUPPLIER;


SELECT CUSTOMER.NMCUSTOMER, CASE 
WHEN GROUPING(PRODUCT.NMPRODUCT) = 1 THEN 'TOTAL'
ELSE NMPRODUCT END AS NMPRODUCT , 
SUM(PRODUCT.CDPRODUCT) AS TOTALBOUGHT
FROM PRODUCTREQUEST  
FULL JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
FULL JOIN REQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
FULL JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
GROUP BY NMCUSTOMER, ROLLUP(NMPRODUCT)
ORDER BY NMCUSTOMER;

SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE FROM REQUEST 
FULL JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
GROUP BY NMCUSTOMER, IDFONE, REQUEST.CDCUSTOMER
HAVING REQUEST.CDCUSTOMER = NULL;

SELECT SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE FROM PRODUCT
FULL JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY NMSUPPLIER, IDFONE, PRODUCT.NMPRODUCT
HAVING NMPRODUCT = 'leite em po' OR NMPRODUCT = 'agua mineral';

SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER FROM PRODUCTREQUEST
FULL JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
FULL JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
GROUP BY NMPRODUCT, NMSUPPLIER
HAVING COUNT(PRODUCT.CDPRODUCT) > 3;

