SELECT DISTINCT PRODUCT.NMPRODUCT FROM PRODUCTREQUEST 
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT;

SELECT PRODUCT.NMPRODUCT FROM PRODUCTREQUEST 
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT GROUP BY NMPRODUCT;

SELECT PRODUCT.NMPRODUCT, COUNT(PRODUCT.NMPRODUCT) AS TIMESBOUGHT, SUM(QTAMOUNT) AS AMOUNTBOUGHT FROM PRODUCTREQUEST 
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT GROUP BY NMPRODUCT

SELECT SUPPLIER.NMSUPPLIER, SUM(QTSTOCK) AS TOTALSTOCK, (SUM(VLPRICE) / COUNT(VLPRICE)) AS AVERAGEPRICE, COUNT(NMPRODUCT) AS PRODUCTSAMOUNT 
FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER 
GROUP BY NMSUPPLIER;

SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE, MAX(VLTOTAL) AS HIGHESTPRICE, MIN(VLTOTAL)AS LOWESTPRICE, SUM(VLTOTAL) AS TOTALPRICE, (SUM(VLTOTAL)/COUNT(VLTOTAL)) AS AVERAGEPRICE 
FROM REQUEST INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER 
GROUP BY CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE, VLTOTAL ORDER BY VLTOTAL DESC;

SELECT REQUEST.DTREQUEST, CUSTOMER.NMCUSTOMER, COUNT(DISTINCT CDPRODUCT) AS QTDPRODUCTS, SUM(VLUNITARY * QTAMOUNT) AS VLTOTAL , (SUM(VLUNITARY)/SUM(QTAMOUNT)) AS VLAVERAGE FROM PRODUCTREQUEST
INNER JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
GROUP BY REQUEST.DTREQUEST, CUSTOMER.NMCUSTOMER ORDER BY COUNT(DISTINCT CDPRODUCT);

SELECT SUPPLIER.NMSUPPLIER, COUNT(DISTINCT PRODUCT.NMPRODUCT) AS QTPRODUCTS
FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER 
GROUP BY NMSUPPLIER
HAVING COUNT(DISTINCT PRODUCT.NMPRODUCT) != 0;

SELECT PRODUCT.NMPRODUCT, SUM(PRODUCTREQUEST.CDPRODUCT) AS QTDBOUGHT, SUM(QTAMOUNT) AS TOTALBOUGHT FROM PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY NMPRODUCT
HAVING SUM(PRODUCTREQUEST.CDPRODUCT)> 2
ORDER BY SUM(PRODUCTREQUEST.CDPRODUCT);

SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, SUM(PRODUCTREQUEST.VLUNITARY) AS TOTALPRICE , SUM(PRODUCTREQUEST.CDPRODUCT) AS QTDREQUESTED, SUPPLIER.NMSUPPLIER FROM PRODUCTREQUEST
INNER JOIN REQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN CUSTOMER ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
INNER JOIN SUPPLIER ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
GROUP BY CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER
HAVING SUM(PRODUCTREQUEST.VLUNITARY) > 1000
ORDER BY CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT;
