DELETE REQUEST FROM REQUEST 
LEFT JOIN PRODUCTREQUEST ON PRODUCTREQUEST.CDREQUEST = REQUEST.CDREQUEST
WHERE VLTOTAL < 1000 
OR NOT EXISTS (SELECT * FROM PRODUCTREQUEST WHERE REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST)
OR DTREQUEST >= '20030601' OR DTREQUEST <= '20030630';

UPDATE PRODUCT SET VLPRICE = (SELECT AVG(VLUNITARY) FROM PRODUCTREQUEST WHERE PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT GROUP BY CDPRODUCT)
FROM PRODUCTREQUEST WHERE (SELECT SUM(QTAMOUNT) FROM PRODUCTREQUEST WHERE PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT) > 800;

INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, IDFONE) 
SELECT (SUPPLIER.CDSUPPLIER + MAX(PRODUCT.VLPRICE)), NMSUPPLIER, IDFONE FROM SUPPLIER 
INNER JOIN PRODUCT ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER 
GROUP BY SUPPLIER.CDSUPPLIER, NMSUPPLIER, IDFONE;

UPDATE REQUEST SET DTDELIVER = DTREQUEST + 30 FROM REQUEST WHERE (DTDELIVER - (DTREQUEST + 10)) < 10 OR VLTOTAL < 10000